// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsZDg-e2cLrq-eRxXYTd8KGLRQVjrFydw',
    appId: '1:372037210740:web:78811e5f78cc97f80cb721',
    messagingSenderId: '372037210740',
    projectId: 'expenseflow-f3c18',
    authDomain: 'expenseflow-f3c18.firebaseapp.com',
    storageBucket: 'expenseflow-f3c18.firebasestorage.app',
    measurementId: 'G-FFH4E15PJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3MwJCOqNcJYHLbUtXXn4rMdkW8Ty61z8',
    appId: '1:372037210740:android:e6e8c783cb892bd00cb721',
    messagingSenderId: '372037210740',
    projectId: 'expenseflow-f3c18',
    storageBucket: 'expenseflow-f3c18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs9lOFEOShy15UjlpCPevHwnf2sISZ5ns',
    appId: '1:372037210740:ios:05b1d42ff83807f00cb721',
    messagingSenderId: '372037210740',
    projectId: 'expenseflow-f3c18',
    storageBucket: 'expenseflow-f3c18.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs9lOFEOShy15UjlpCPevHwnf2sISZ5ns',
    appId: '1:372037210740:ios:05b1d42ff83807f00cb721',
    messagingSenderId: '372037210740',
    projectId: 'expenseflow-f3c18',
    storageBucket: 'expenseflow-f3c18.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsZDg-e2cLrq-eRxXYTd8KGLRQVjrFydw',
    appId: '1:372037210740:web:18a9e349199a73b50cb721',
    messagingSenderId: '372037210740',
    projectId: 'expenseflow-f3c18',
    authDomain: 'expenseflow-f3c18.firebaseapp.com',
    storageBucket: 'expenseflow-f3c18.firebasestorage.app',
    measurementId: 'G-RH8RQ4P8B8',
  );
}
